### ISSUE TITLE
Keras dependency could be replaced by tf.keras

### ISSUE THREAD

**Issue by lostanlen** [BirdVox/birdvoxclassify#1]
See https://github.com/BirdVox/birdvoxdetect/issues/2

**Comment by lostanlen** [comment]
update: upon reflection, we have decided to stick to keras in order to allow GPU prediction

**Comment by justinsalamon** [comment]
Note for posterity: Jong Wook noticed some unexpected behavior when trying to replace keras with tf.keras in CREPE. I would be very wary of this move without 100% test coverage including regression tests to ensure behavior doesn't change.

**Comment by lostanlen** [comment]
noted
