### ISSUE TITLE
Put higher-order taxa in the plural form in the taxonomy

### ISSUE THREAD

**Issue by lostanlen** [BirdVox/birdvoxclassify#11]
raised by Andrew Farnsworth

Passeriforme -> Passeriformes
Pelecaniforme -> Pelecaniformes

This is relatively urgent. Triaged for v0.3

**Comment by jtcramer** [comment]
Sorry for taking so long to get to this. I'm thinking to avoid uploading an entirely new model file to ensure md5-checksum consistency with the updated taxonomy files, we can try adding (relative) symlinks to the models in the `models` branch renamed to have the checksum of the updated taxonomy. This way we get backwards compatibility without doubling the space we need for. As far as I know, git should handle symlinks with relative grace. What are your thoughts?

**Comment by justinsalamon** [comment]
I have no strong opinions. @lostanlen ?

**Comment by lostanlen** [comment]
yes

**Comment by jtcramer** [comment]
Addressed by #12.
