### ISSUE TITLE
Solve compatibility issues with Tensorflow 2.x

### ISSUE THREAD

**Issue by jtcramer** [BirdVox/birdvoxclassify#2]
In order to maintain compatibility with BirdVoxDetect, we need to make sure that this is compatible with Tensorflow 1.12.2. This could be solved as simply as changing the Keras dependency to be >=2.1.6, though we may need to retrain a model using the corresponding version of Tensorflow. Currently models are trained with Tensorflow 1.14.

**Comment by lostanlen** [comment]
what's the way out of this? can i update the Keras dependency now?

**Comment by justinsalamon** [comment]
As noted on BVD, sounds like we need to add some regression tests. If the tests fail and we need to re-train, we should consider bumping all the way up to 2.x, no?

**Comment by lostanlen** [comment]
i agree with @justinsalamon . it's high time be bump up to at least 2.2

**Comment by lostanlen** [comment]
triaged for BVD v0.4
no change required on BVC's end

**Comment by jtcramer** [comment]
Addressed by a657ef946a1a47a825d0e897b164ce3a6324a0d8
