### ISSUE TITLE
bug in get_model_path 

### ISSUE THREAD

**Issue by lostanlen** [BirdVox/birdvoxclassify#3]
it looks like `get_model_path` sometimes returns the wrong path where the HDF5 model belongs, thus causing installation issues in bvd v020-alpha:

See:
https://travis-ci.org/BirdVox/birdvoxdetect/jobs/619916739

**Comment by jtcramer** [comment]
The issue was due to forgetting the way pip installations copy code/resources to the site-packages directory. To fix this I'm simply moving the resources folder inside of the module instead of in the project directory.

**Comment by jtcramer** [comment]
Resolved by #4.

**Comment by lostanlen** [comment]
Wonderful, thanks!
