### ISSUE TITLE
Probabilistic outputs

### ISSUE THREAD

**Issue by lostanlen** [BirdVox/birdvoxclassify#9]
@bmvandoren had a good suggestion today: have BVC return probabilistic estimates for each taxon, rather than simply the argmax.

@jtcramer thoughts? i would guess that this would require a dedicated function in `core.py`
i can write the rest within BirdVoxDetect so that the probabilities are tabulated as a Pandas DataFrame and exported as comma-separated values

**Comment by jtcramer** [comment]
It seems that this happens on BVD's side: https://github.com/BirdVox/birdvoxdetect/blob/master/birdvoxdetect/core.py#L815

**Comment by jtcramer** [comment]
The JSON object returned from BVC's formatting should contain all taxa.

**Comment by lostanlen** [comment]
@jtcramer thank you for your help! in this case i will update BVD accordingly 😊
